# Generated by Django 3.2.16 on 2022-12-14 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paquetes',
            fields=[
                ('servicio', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('length', models.DecimalField(decimal_places=1, max_digits=5)),
                ('width', models.DecimalField(decimal_places=1, max_digits=5)),
                ('height', models.DecimalField(decimal_places=1, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=1, max_digits=5)),
                ('pickupAdd', models.CharField(max_length=20)),
                ('pickupCity', models.CharField(max_length=20)),
                ('recipientName', models.CharField(max_length=20)),
                ('recipientId', models.IntegerField()),
                ('deliveryAdd', models.CharField(max_length=20)),
                ('deliveryCity', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('user', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
    ]
