# Generated by Django 3.2.16 on 2022-12-14 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquetes',
            name='servicio',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
