# Generated by Django 3.2.16 on 2022-12-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBase', '0002_alter_paquetes_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquetes',
            name='servicio',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
