# Generated by Django 3.2.16 on 2022-12-30 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBase', '0003_alter_paquetes_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(max_length=64),
        ),
    ]
